### ISSUE TITLE
Empty fields in address_components list when request a regular address

### ISSUE THREAD

**Issue by fcjbispo** [velyo/google-maps-services#10]
### Installed product versions
- GoogleMapsClient: NET45

### Description
I am getting empty results for some fields on address_components when running a request on Google Maps API.

### Steps to recreate
In a C# NET45 console project, run the code below in Main static method:
--
            MapsApiContext _context = MapsApiContext.Default;

            // Console.WriteLine("API Key is {0}", _context.ApiKey);

            GeocodingRequest geocodingRequest = new GeocodingRequest("1 Microsoft Way, Redmond, CA", _context);
            GeocodingResponse gmapResponse = geocodingRequest.GetResponse();

            foreach (var r in gmapResponse.Results)
            {
                Console.WriteLine("Latitude/Longitude is {0}/{1}", r.Geometry.Location.Latitude, r.Geometry.Location.Longitude);
                Console.WriteLine("Formatted Address is {0}", r.FormattedAddress);

                int l = 0;
                foreach (var ac in r.AddressComponents)
                {
                    Console.Write("Address Components[{0}] are '{1}' and '{2}' of types [", l++, ac.ShortName, ac.LongName);
                    for (int i = 0; i < ac.Types.Length; i++)
                        Console.Write(" {0} ", ac.Types[i]);
                    Console.WriteLine("]");
                }

            }
            Console.WriteLine("------");
            Console.WriteLine("Press any key...");
            Console.ReadLine();
--
### Current behavior
The execution response was:
--
Latitude/Longitude is 47,6393225/-122,1283833
Formatted Address is 1 Microsoft Way, Redmond, WA 98052, USA
Address Components[0] are '' and '' of types [ street_number ]
Address Components[1] are '' and '' of types [ route ]
Address Components[2] are '' and '' of types [ neighborhood  political ]
Address Components[3] are '' and '' of types [ locality  political ]
Address Components[4] are '' and '' of types [ administrative_area_level_2  political ]
Address Components[5] are '' and '' of types [ administrative_area_level_1  political ]
Address Components[6] are '' and '' of types [ country  political ]
Address Components[7] are '' and '' of types [ postal_code ]
Address Components[8] are '' and '' of types [ postal_code_suffix ]
------
Press any key...
--

### Expected behavior
The values for each address component should have the respective information as described by its type

**Comment by velyo** [comment]
Thanks a lot. I'm giong to investigate that.

**Comment by fcjbispo** [comment]
thank you!
